FROM alpine:3.15

ARG TARGETPLATFORM
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

RUN apk add --no-cache \
    curl \
    linux-headers \
    build-base \
    make \
    libxml2-dev \
    linux-lts-dev \
    linux-lts \
    clang-libs \
    llvm12 \
    llvm12-libs \
    llvm12-dev \
    llvm12-static

RUN llvm-config --version | grep -q '^12'

# Alpine 3.15 only supports LLVM 12 so fix Rust 1.55
RUN curl https://sh.rustup.rs -sSf > rustup.sh \
    && sh rustup.sh -y \
          --default-toolchain 1.55 \
          --profile minimal \
          --no-modify-path \
    && rm -f rustup.sh \
    && rustup component add rustfmt \
    && rustup --version \
    && cargo -vV \
    && rustc -vV

# Can not extract vmlinux or btf from the vmlinuz image.

WORKDIR /build
