FROM ubuntu:21.04

ARG TARGETPLATFORM
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y install \
    curl \
    wget \
    build-essential \
    software-properties-common \
    lsb-release \
    libelf-dev \
    linux-headers-generic \
    && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 13 && rm -f ./llvm.sh
RUN apt-get -y install \
    "linux-image-$(ls /lib/modules)" \
    && apt-get clean -y

RUN ln -s /usr/bin/llvm-config-13 /usr/bin/llvm-config
RUN llvm-config --version | grep -q '^13'

# Install current stable Rust. The first goal of RedBPF build test is to
# support latest Rust release.
RUN curl https://sh.rustup.rs -sSf > rustup.sh \
    && sh rustup.sh -y \
          --default-toolchain stable \
          --profile minimal \
          --no-modify-path \
    && rm -f rustup.sh \
    && rustup component add rustfmt \
    && rustup --version \
    && cargo -vV \
    && rustc -vV

COPY extract-btf-aarch64.rs .

RUN if [ x$TARGETPLATFORM = x"linux/arm64" ]; then \
      rustc extract-btf-aarch64.rs \
      && gzip -dc /boot/vmlinuz | ./extract-btf-aarch64 /dev/stdin /boot/vmlinux-btf; \
    else \
      /lib/modules/*/build/scripts/extract-vmlinux /boot/vmlinuz > /boot/vmlinux; \
    fi
RUN rm -f extract-btf-aarch64.rs

WORKDIR /build
