FROM ubuntu:18.04

ARG TARGETPLATFORM
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y install \
    curl \
    wget \
    build-essential \
    software-properties-common \
    lsb-release \
    libelf-dev \
    linux-base \
    libkmod2 \
    kmod \
    && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 13 && rm -f ./llvm.sh

RUN ln -s /usr/bin/llvm-config-13 /usr/bin/llvm-config
RUN llvm-config --version | grep -q '^13'

# Install kernel v4.19 to check the oldest supported kernel
WORKDIR /tmp/kernel
RUN if [ x$TARGETPLATFORM = x"linux/arm64" ]; then \
      wget \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-headers-4.19.5-041905-generic_4.19.5-041905.201812031110_arm64.deb \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-image-4.19.5-041905-generic_4.19.5-041905.201812031110_arm64.deb \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-modules-4.19.5-041905-generic_4.19.5-041905.201812031110_arm64.deb \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-headers-4.19.5-041905_4.19.5-041905.201812031110_all.deb; \
    else \
      wget \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-headers-4.19.5-041905-generic_4.19.5-041905.201812031110_amd64.deb \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-image-unsigned-4.19.5-041905-generic_4.19.5-041905.201812031110_amd64.deb \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-modules-4.19.5-041905-generic_4.19.5-041905.201812031110_amd64.deb \
      https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.5/linux-headers-4.19.5-041905_4.19.5-041905.201812031110_all.deb; \
    fi; \
    dpkg -i linux-*4.19.5*.deb
WORKDIR /
RUN rm -rf /tmp/kernel

# Install current stable Rust. The first goal of RedBPF build test is to
# support latest Rust release.
RUN curl https://sh.rustup.rs -sSf > rustup.sh \
    && sh rustup.sh -y \
          --default-toolchain stable \
          --profile minimal \
          --no-modify-path \
    && rm -f rustup.sh \
    && rustup component add rustfmt \
    && rustup --version \
    && cargo -vV \
    && rustc -vV

# Ubuntu18.04 does not support the Linux kernel that contains BTF section.

WORKDIR /build
